name: Build hev-socks5-tunnel armv7

on:
  workflow_dispatch: # Hanya trigger ini yang dipertahankan untuk manual run

jobs:
  build-so:
    name: Build jniLibs armv7
    runs-on: ubuntu-latest

    steps:
      - name: Buat Workspace & Clone Source Code
        run: |
          mkdir build-workspace
          cd build-workspace
          
          # ndk-build mengharuskan direktori bernama 'jni'
          # Flag --recursive untuk menarik seluruh submodule project C-nya.
          git clone --recursive https://github.com/heiher/hev-socks5-tunnel jni

      - name: Compile dengan ndk-build (armeabi-v7a)
        run: |
          cd build-workspace
          
          # Menggunakan Android NDK bawaan server Ubuntu GitHub.
          # Parameter APP_ABI=armeabi-v7a untuk build arsitektur armv7.
          $ANDROID_NDK_LATEST_HOME/ndk-build APP_ABI=armeabi-v7a

      - name: Upload .so File sebagai Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hev-socks5-tunnel-armeabi-v7a
          path: build-workspace/libs/armeabi-v7a/*.so
          retention-days: 14
